### ISSUE TITLE
'LED' does not name a type on 3rd party core. 

### ISSUE THREAD

**Issue by DashApple** [teddokano/LEDDriver_NXP_Arduino#3]
Hi, I do appologise in advance if this is an overlook by myself. 

I have been using this libary with an arduino UNO, 328P uisng the default uno board that comes with the arduino IDE.

I have had no issues with it running and had a clock working as hopped. I have started to migrate over to the 1284P and as I understand this should work. I have the MightyCore for board support but now during the compiling I get the errors

'LED' does not name a type and hours, seconds ect was not declared in scope, No changes to the code, just going from the UNO inbuilt to the MightyCore, I have tried the MiniCore with the 328P and I get the same error. 

I am unsure where to ask first and understand this may have nothing to do with the libary but wanted to ask. 

![I2C](https://github.com/teddokano/LEDDriver_NXP_Arduino/assets/134227985/331bca70-ab5d-407b-a279-4186f42a09b3)

**Comment by teddokano** [comment]
Hi!
Thank you for using this library and finding the problem.  

I released 1.0.2 which can fix the problem.  
I'd appreciate if you can try it. 

#### Problem:
I tried the compile my [sample code](https://github.com/teddokano/LEDDriver_NXP_Arduino/blob/main/examples/concept_examples/abstracting_LEDs/abstracting_LEDs.ino) with MightyCore and got same error which you found. 

 The cause of the problem is, the class name:`LED` which is used in MightyCore as [a global variable](https://github.com/MCUdude/MightyCore/blob/47af83c3eae6f393cf1cdd62cbb1347fa5a799c3/avr/variants/sanguino/pins_arduino.h#L54) also. 

I was trying to find easy way to fix like just adding a new line in source code but I couldn't.  
Instead of fixing the conflict in simple way, I updated the library to have different name. It is `_LED` (an underscore before the 'LED') which performs just as same as `LED`.    

#### Solution

The `_LED` can solve compile error when it uses MightyCore.  
All you need to do is just replacing the class name from `LED` to `_LED`.  

The changing your code may be troublesome but please try this. 

```cpp
include <LED.h>  // Please keep this as <LED.h> (not <_LED.h>)
...
...  // All following class definitions are need to be "_LED"
...
_LED hours [] = {
    _LED(&H1, H), _LED(&H1, G), _LED(&H1, F), _LED(&H1, E),
    _LED(&H1, D), _LED(&H1, C), _LED(&H1, B), _LED(&H1, A) ,
    ...
｝;
```

**Comment by DashApple** [comment]
Hi, Thankyou for the reply and update to the libary, very much appreciated. 

I can confirm I have compiled it on both the mini and mighty cores without issues after the change :)

![I2C2](https://github.com/teddokano/LEDDriver_NXP_Arduino/assets/134227985/37264eb6-5a2f-48d0-9b2d-6c2e5bff0aa8)

**Comment by teddokano** [comment]
Thank you for confirming. 
Hoping this library helps your great app! ;)
